### ISSUE TITLE
Ask people if they are sure they want to sign up as maintainer

### ISSUE THREAD

**Issue by alloy** [DefinitelyTyped/dt-mergebot#202]
It happens too often that people mistake the ‘by’ header for _just_ a list of people that contributed to a file, not realising it means they are signing up to be a maintainer and getting pinged for each issue/PR. E.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48868#discussion_r510079733

It is cumbersome to manually ask this in a review and also might stall a PR longer than necessary if a bot could respond much faster. Is this the right place for that?

**Comment by elibarzilay** [comment]
Yes, this is the right place.

One thing that I didn't like is how there are sometimes PRs that are big enough and/or noisy enough so it's easy to miss the fact that there's a new owner.  But I didn't realize that it is also common enough to add yourself to the list thinking that this is some required signing thing for all contributors...

So to kill both birds, maybe add some code that will add a label and/or text when a PR has any changes to the owners list?

The other issue here is the mistake of using an email (similar to people who leave it as `.../me`).  So maybe I'll also add code to verify that the change (adding/removing) is always for the PR author.  Non matches would be reported in the comment (so authors can quickly fix them) and also require a maintainer eyeball (to allow dropping unresponsive people.

**Comment by alloy** [comment]
> So to kill both birds, maybe add some code that will add a label and/or text when a PR has any changes to the owners list?

A text comment [ideally on the change] would definitely be helpful to the author 👍 

I in turn didn’t realise it was an issue that people reviewing types of many packages might miss, so a label sounds great for that indeed.

> The other issue here is the mistake of using an email (similar to people who leave it as `.../me`). So maybe I'll also add code to verify that the change (adding/removing) is always for the PR author. Non matches would be reported in the comment (so authors can quickly fix them) and also require a maintainer eyeball (to allow dropping unresponsive people.

👌

**Comment by elibarzilay** [comment]
Given the replies in DefinitelyTyped/DefinitelyTyped#49034, I think that it would be good to add a pointer to the readme section about owners to that text.

**Comment by elibarzilay** [comment]
So, after some thinking, I've made #221, which adds lists of added/removed owners in the welcome comment, and also adds an `Edits Owners` label to PRs that do so unless they're for new/removed packages.

It doesn't address the feature request here completely --- specifically, there's no "are you sure?" comment.  Adding such information should be easy, but I worry about making it too verbose to be useful.  So hopefully the current additions will improve it by making the owner edits much more visible to the author and to reviewers.

If not, we can re-open it.  FWIW, if such a comment is deemed useful in the future, it would be very easy to add it.  And BTW, if/when this issue is indeed reraised: I thought might make sense is to add the "are you sure?" comment if a PR adds the author to a package that already has >N owners.

**Comment by alloy** [comment]
Thanks for taking the time thus far!

However, I think this ask should remain open. I think the “do you realise what it means to sign-up as owner?” question will clearly explain to people that this is not simply a list of people that have ever contributed to the typings, whereas the “added owner” label may simply re-affirm to them what they _thought_ they did.

**Comment by elibarzilay** [comment]
@alloy, and ping @orta too:

OK, so maybe a compromise between a new comment and none at all:

* When the author added themselves to at least one package that *already has 4 authors*

* And the author is
  1. not *already an owner* of another package in the same PR, **or**
  2. a first-time contributor (determined by `CommentAuthorAssociation.FIRST_TIME_CONTRIBUTOR`), **or**
  3. already an owner of *any package*

* Then add an "are you sure" comment *to the welcome message*, with a pointer to the readme section about owners.

Re the choices in the second item: (3) would be hard(er) to implement since it's not used now, and it depends on reading CONTRIBUTORS (on every invocation of the bot, which is a lot), (1) is easy, and (2) is also easy and is already used for displaying the "I see this is your first time" text.

Which one is your preference?

----

Explanations for the rest: The reason for 4 is "one, two, three, many" (very science).  A separate comment would be too noisy, but for newbies, my assumption is that they will actually read the whole welcome comment, so there's no need for a separate comment.

**Comment by elibarzilay** [comment]
I added this, it looks as follows (I ran it with fake data to see how it looks, the pr it comes from has no owner changes):

![image](https://user-images.githubusercontent.com/185905/98859057-97932d80-242f-11eb-9267-75dbcfdb4be6.png)

**Comment by alloy** [comment]
Great! That all looks like reasonable choices to me, so let’s give it a try 👍 

Thanks for all the work on this, much appreciated 🙏

**Comment by elibarzilay** [comment]
@alloy Thanks!  -- I hope to get it merged later today.
