### ISSUE TITLE
Requires to change tests when only comments were changed

### ISSUE THREAD

**Issue by Maxim-Mazurok** [DefinitelyTyped/dt-mergebot#203]
For example, in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49035

Only comments were changed. So, bot doesn't allow to auto-merge this PR.

It would be great if it could ignore non-code changes.

**Comment by elibarzilay** [comment]
I don't see a good way to do that.

Parsing the file might be possible in a quick + easy way at some point if the lightweight syntax server can be used to quickly scan a file and determine which parts are comments.  But then there are JSDoc comments, and comments containing special text that affect TS (`// @ts-ignore`), or the linter, or any external tools.

And even if there is a way to find only non-meaningful comments, what about a PR that changes a description in some wrong way?  For example, that PR could have had

    // Generated from: htps://analytics.googleapis.com/$discovery/rest?version=v3

So I think that ignoring comments for any purpose is impractical.

The real problem in that PR is that it was waiting for an approval because it was an untested pr.  We'd definitely be happy to find more ways to determine if there's no need for tests: faster turnaround time for you and less work for us.  If I had infinite time resources, I can imagine some code that summarizes all the type information from a given file (I think that much of that code exists in the TS tests --- see the `.types` files), and if that information is the same between the old and the new versions, then there's no need for tests.

But IME very few PRs don't do any type changes, and those that *are* in that category are easy enough that they're merged pretty quickly, so putting time in that is not useful.  (What I'd really like to see is something like coverage percentage, then allow PRs that keep it the same or smaller --- that would encourage a gradual improvement of the tests; but at least in its current shape, something like that should be done by the CI builds instead of in the bot, something similar to the benchmark build.)

**Comment by Maxim-Mazurok** [comment]
Fair enough, thank you for merging.

I guess I will have to solve this by adding some garbage (like last updated timestamp) to test files. Apparently, updating revision number in tests sometimes doesn't cut it...

Though I'd try my luck here before changing my bot :) Thanks for a prompt response!

**Comment by elibarzilay** [comment]
@Maxim-Mazurok, like I said in the other thread, you can certainly come up with ways to circumvent things like this, but in this case I don't think that there's a need to do so, since for such minor changes I'm guessing that everyone else would do what I'd do -- it's easy to see that the change is small and not affecting any of the semantics, and therefore everyone would authorize it quickly.

BTW, we also have a procedure in place to "bless" PRs so they can be self-merged despite whatever got them on the maintainer queue.  If you post a "ready to merge" comment, and then the maintainer in the current cycle blesses it (rather than merging it), then the PR would get immediately merged.

**Comment by Maxim-Mazurok** [comment]
I see your point. But the ultimate goal of this project is to be updated ASAP and without any human help.

By the way, I found an interesting bug (in GitHub?) that doesn't let me auto-merge PRs. You might want to take a look at this issue: https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/383

**Comment by elibarzilay** [comment]
Well, the DT procedures are probably going to change at some point, so I don't know how feasible it is to do this in the long run.  (If you really want to do it completely automatic, then maybe it makes sense to push your own typing package to npm and make the DT one depend on it so it gets installed?  I'm not familiar with things enough to know if this is doable though.)

Re that bug: it looks like you sent the merge comment right after the PR was done (probably automatically), so it wasn't merged because the bot was still starting things and waiting for the CI build.  Later there's the force-push (which might be bogus according to your description) which means that the earlier ready-to-merge comment is ignored now, and it will try to merge when you post it again.  Another side-note: you can click the "diagnostic information" thing to see the information that the bot has on this PR.  (This is updated on every interaction and also by a daily every midnight EST, and probably on other times too since I'm working on the bot now.)

(One last comment: it would be good to leave a comment if you don't want it merged.  I'd do that but I don't know if you're careful not to comment on it.)

**Comment by Maxim-Mazurok** [comment]
> push your own typing package to npm and make the DT one depend on it

That's an interesting idea... Thanks!

> Re that bug

Yes, so every time I update, I do a force push. And for some reason, GitHub recorded this push to be after I opened PR. But it's clear from logs and implementation, that I always do push before opening PR. I even wait about 10 seconds after pushing, before opening PR. So yeah, I thought that this might be dt-mergebot issue, but then I looked at timestamps in HTML of this page and realized that it's a git/github bug probably.
