### ISSUE TITLE
Fails to comment on huge PRs

### ISSUE THREAD

**Issue by Maxim-Mazurok** [DefinitelyTyped/dt-mergebot#447]
TL;DR: when opening huge PRs, such as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62106 - mergebot never picks it up.

> Someone would need to [log into the azure functions](https://github.com/DefinitelyTyped/dt-mergebot/#meta ) to read the logs to know exactly why, but there is a 'too big to review' style check in the bot which this doesn't seem to be getting hit with.
> _Originally posted by @orta in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62106#issuecomment-1242663828_

Other huge PRs that it didn't pick up:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61722
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62194
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62193
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62192

**Comment by Maxim-Mazurok** [comment]
Hi guys, any idea how to fix this? We've [removed `// TypeScript Version`](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/688) from types and I'd like to create a PR to update all `gapi.client.*` DT types, but I'm afraid that mergebot will fail on a huge PR again. I'm happy to still give it a try if that'll help in your investigation. Perhaps @andrewbranch or @elibarzilay could help? Thank you!

**Comment by Maxim-Mazurok** [comment]
That all makes sense, I was expecting something along those lines, thank you for looking into that and for the quick hopefully-fix :)

PR I'm going to open will likely be just removing the same line from all packages, so I expect it can be easily mass-reviewed using some combination of `git diff` and `uniq` commands, or with an above-mentioned shrug :) I will try to keep non-humanly reviewable PRs to a minimum tho, cheers!

**Comment by elibarzilay** [comment]
Heh, consider the fact that cloning DT takes a good amount of time and space, and that using plain `git` to fetch a PR branch from a different repo can be confusing, and it's not surprising that it's not done too often given the volume of PRs.

But yeah, something like `git diff ... | grep '^[+-]' | grep -vE '^(\+\+\+|---) [ab]/' | sort -u` is probably going to make it easy to scan.  Maybe include instructions for how to fetch the branch and run the diff would make it easier to review if you have more of these in the future...

**Comment by Maxim-Mazurok** [comment]
@elibarzilay the bot didn't comment on this huge PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62446
Even though CI failed, I think it still should've picked it up and commented "The CI build failed", same as in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62399
Might need to re-open this issue, @andrewbranch
Thank you!

**Comment by elibarzilay** [comment]
I tried to run it locally, and it's still a pretty long run, but it takes 6m, which I thought is under the azure function timeout.

The thing that takes most of the time there, BTW, is getting owners for around 460 packages -- I'm guessing that it's slower because it fetches old files which take more time to recover.  It uses the api for that, but ultimately it will end up digging into the git repo to get it all.

Someone (@andrewbranch?) with access to that should look at whether the timeout is shorter than that, and either
* Make it longer if it's 5m
* Make it grab less than 500 files (`TOO_MANY_FILES` in `pr-query.ts`)
* Revise the code to make the queries in parallel (but I doubt that it'll help, since it will probably trigger some GH threshold if it does 460 quick api calls)
